### ISSUE TITLE
Support dragging within flexbox layouts

### ISSUE THREAD

**Issue by danvk** [carlosjorger/fluid-dnd#50]
If you change the demo to use a flexbox layout, drag & drop no longer works how you'd expect.

https://codesandbox.io/p/devbox/unruffled-hooks-c8624s

Here's the basic layout:

<img width="429" alt="Image" src="https://github.com/user-attachments/assets/aeb3104c-7e10-43cf-8891-47255a1bced6" />

But when you drag the "4", it tries to shift entire rows:

<img width="587" alt="Image" src="https://github.com/user-attachments/assets/daad64b3-2d60-41b5-b635-9afd03b9c9b7" />

I'd expect the other boxes to reflow around the 4's tentative spot, kind of like the iOS interaction for rearranging app icons.

```css
.number {
  border-style: solid;
  padding-left: 5px;
  margin-top: 0.25rem;
  border-width: 2px;
  width: 100px;
}
.number-list {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  width: 450px;
  /*
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  padding: 10px;
  column-gap: 1em;
  row-gap: 1em;
  */
}
```
